### ISSUE TITLE
LS2 Won't Compile in ESPhome 2025.10.1

### ISSUE THREAD

**Issue by restauffer** [screekworkshop/screek-light-sensor#7]
I tried to update my LS2 light sensor to ESPHome 2025.10.1 and got the following error message:

INFO ESPHome 2025.10.1
INFO Reading configuration /config/esphome/screek-ligh-sensor.yaml...
Failed config

esp32: [source /config/esphome/screek-ligh-sensor.yaml:19]
  board: lolin_c3_mini
  
  Only Arduino 3.0+ is supported.
  framework: 
    type: arduino
    version: 2.0.7
    platform_version: 6.0.1

The current solution to this  error is:

  Remove the lines:

        version: 2.0.7
        platform_version: 6.0.1

I also tried to switch to type: esp-idf but go the following error:

       /config/esphome/screek-ligh-sensor.yaml: In lambda function:
        /config/esphome/screek-ligh-sensor.yaml:89:14: error: 'temperatureRead' was not declared in this scope
           89 |     unit_of_measurement: °C
              |              ^~~~~~~~~~~~~~
        Compiling .pioenvs/light-sensor-ls2/bootloader_support/src/bootloader_utility.c.o
        Compiling .pioenvs/light-sensor-ls2/bootloader_support/src/flash_partitions.c.o
        /config/esphome/screek-ligh-sensor.yaml: In lambda function:
        /config/esphome/screek-ligh-sensor.yaml:15:28: error: 'ESP' was not declared in this scope
           15 |           id(cpu_speed) = ESP.getCpuFreqMHz(); 

For now, I recommend you update the yaml in this repository to remove the version and platform_version lines but before January, 2026 you will need to fix the underlying code  to work with esp-idf
